// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buaoasayrplrordqngrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1YW9hc2F5cnBscm9yZHFuZ3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTA0MDksImV4cCI6MjA2MDgyNjQwOX0.Ieu07_2Y-YZBHDDXxsesGt8uYvglji3Lu4b67whoOOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);